create table if not exists public.productos (
  id bigint generated by default as identity primary key,
  nombre text not null,
  descripcion text,
  precio numeric(12,2) not null default 0 check (precio >= 0),
  imagen_url text,
  categoria text,
  peso_estimado_g numeric,
  tiempo_estimado_min integer,
  material_defecto_id bigint,
  activo boolean not null default true
);

create table if not exists public.perfiles (
  id uuid primary key references auth.users(id) on delete cascade,
  nombre text,
  rol text not null default 'usuario' check (rol in ('usuario', 'admin')),
  creado_en timestamptz not null default now()
);

create table if not exists public.compras (
  id bigint generated by default as identity primary key,
  user_id uuid references auth.users(id) on delete set null,
  nombre_cliente text not null,
  email_cliente text not null,
  telefono text,
  direccion text,
  total numeric(12,2) not null check (total >= 0),
  detalle jsonb not null default '[]'::jsonb,
  fecha timestamptz not null default now(),
  estado text not null default 'pendiente' check (estado in ('pendiente', 'confirmado', 'enviado', 'cancelado'))
);

alter table public.perfiles enable row level security;
alter table public.compras enable row level security;
alter table public.productos enable row level security;

create or replace function public.es_admin()
returns boolean language sql stable security definer set search_path = public
as $$ select exists (select 1 from public.perfiles where id = auth.uid() and rol = 'admin'); $$;

create policy "perfiles propios" on public.perfiles for select using (id = auth.uid() or public.es_admin());
create policy "catálogo público activo" on public.productos for select to anon, authenticated using (activo = true or public.es_admin());
create policy "compras públicas insertables" on public.compras for insert to anon, authenticated with check (user_id is null or user_id = auth.uid());
create policy "usuarios ven sus compras" on public.compras for select to authenticated using (user_id = auth.uid() or public.es_admin());
create policy "admins gestionan compras" on public.compras for all to authenticated using (public.es_admin()) with check (public.es_admin());

create or replace function public.crear_perfil()
returns trigger language plpgsql security definer set search_path = public
as $$ begin insert into public.perfiles (id, nombre) values (new.id, new.raw_user_meta_data->>'nombre'); return new; end; $$;
drop trigger if exists crear_perfil_al_registrar on auth.users;
create trigger crear_perfil_al_registrar after insert on auth.users for each row execute procedure public.crear_perfil();
